version: '3.9'
services:
  spotify-bot:
    image: node:lts-alpine
    working_dir: /spotify-bot
    container_name: spotify-bot
    build: ./
    env_file:
      - .env
    volumes:
      - ./data:/spotify-bot/data